### ISSUE TITLE
i and l doesn't work together

### ISSUE THREAD

**Issue by cesards** [chrismwendt/bront#18]
Hi!

First of all, very good job! I was using `Dejavu Sans Mono` font until I discovered your repo!

I've realized coding for a while that I would get rid of the `i` top sticky, as you do in `l`

Using your font, have a look to this code

``` java
private int height;
private long club;
```

Doesn't it look weird?

**Comment by chrismwendt** [comment]
Removing the lateral serif on `i` would certainly make it more consistent, but unfortunately more difficult to discern as well. I considered this in #16  and ultimately decided to keep the serif. After using the font extensively both before and after the change, I much prefer the clarity of the serif over the consistency of dropping it, and I hope you would agree.

I'm glad you like the font!
