### ISSUE TITLE
Support for ligatures

### ISSUE THREAD

**Issue by cesards** [chrismwendt/bront#19]
Hi @chrismwendt!

I'm a big fan of this font. I discovered Dejavu Sans years ago and the little changes you made are awesome. 

I'm a developer myself and I love UX & UI. I'm into tooling and I really love trying to improve the experience while coding. The only reason why I haven't been using this font in all my main IDE (IntelliJ) it's because it doesn't support ligatures. Nowadays with trends like Functional Programming, Reactive Programming and modern languages in general, using lambadas is a thing, and I think it would be great if somehow this font could integrate the ligatures Fira Code has!

https://github.com/tonsky/FiraCode

Is this font still being maintained?

Thank you so much in advance!

**Comment by chrismwendt** [comment]
Hey, I'm glad you like it 🙂 I still use deja Vu sans mono bront everywhere, and I'd like you to be able to as well. However, I don't use ligatures, and adding support for them would probably need to come from another collaborator, as long as ligatures are opt-in. I'll add you as a collaborator if you're interested in adding support!

**Comment by cesards** [comment]
Perfect! Good to know :)

I'll add creating ligatures to my todos queue :-P and I might create a PR in the future, hehe.

Good job! 👍

**Comment by cesards** [comment]
BTW, I wanted to ask you, since you created the font. Is there a tool (online or local) you would recommend me to edit the font and add the ligatures? I have in my mind that it shouldn't be complicated since I'm not creating a typography, just merging letters (symbols).

Thanks in advance :)

**Comment by chrismwendt** [comment]
Yeah, I used some tools listed in the readme, but I don't know how to make ligatures
