### ISSUE TITLE
Usage with simple terminal (st)

### ISSUE THREAD

**Issue by brihadeesh** [chrismwendt/bront#23]
This is very likely irrelevant! 

When set to use the *Bront* version of Ubuntu Mono, `st` somehow defaults to using the regular Ubuntu Mono, i.e. no ligatures, off-centre asterisks, and the lot. I'm assuming this is because of the naming (i.e. having a hyphenated name). I'm fairly new to C and since `st` is configured by modifying source code in C, could you suggest a way to bypass/overcome this?

**Comment by bencollerson** [comment]
I had almost the same problem. Here is a solution if anyone else has the problem.

info here: https://wiki.archlinux.org/title/Font_configuration/Examples#Default_fonts

something like this.
```
$ cat .config/fontconfig/fonts.conf
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
        <alias>
                <family>monospace</family>
                <prefer>
                        <family>DejaVu Sans Mono - Bront</family>
                        <family>DejaVu Sans Mono</family>
                        <family>Noto Sans Mono</family>
                        <family>Inconsolata</family>
                        <family>Droid Sans Mono</family>
                        <family>Roboto Mono</family>
                </prefer>
        </alias>
</fontconfig>
```

Verify it works like this:
```
$ fc-match mono
DejaVuSansMono-Bront.ttf: "DejaVu Sans Mono - Bront" "Bront"
```

Then you can compile st using font "mono:...

**Comment by brihadeesh** [comment]
Ah shite, I'd completely forgotten I'd opened this issue (I've since moved to Wayland and foot/alacritty neither of which has this issue).

Thanks though.
